### ISSUE TITLE
a pypi package ?

### ISSUE THREAD

**Issue by stonebig** [altair-viz/schemapi#1]

**Comment by jakevdp** [comment]
Yep, as soon as I figure out what I want to name this package :smile:

**Comment by jakevdp** [comment]
Also some better docs would be nice...

**Comment by jakevdp** [comment]
Renamed to ``schemapi``. I'll add some examples to the README and do a PyPI release soon.

**Comment by jakevdp** [comment]
Done! https://pypi.python.org/pypi/schemapi
