### ISSUE TITLE
pip install on PyCharm for version 0.3.0 did not generate SchemaModuleGenerator Class

### ISSUE THREAD

**Issue by rsloma-ford** [altair-viz/schemapi#9]
Only have JSONSchema and JSONSchemaPlugin available. Therefore, after putting "import schemapi" and then api = schemapi.SchemaModuleGenerator(schemaFilename, root_name='MachineData'), when executing it gives me the error module 'schemapi' has no attribute 'SchemaModuleGenerator'.

Never had an issue like this from python libraries I have added in the past and could use some guidance on how to resolve this. Was looking forward to investigating using this api to help generate json payloads from data that I have acquired and mapped to python dictionaries using a schema.

Please advise.

Thanks,

Bob Sloma

**Comment by jakevdp** [comment]
THe issue is that the pypi release is far out of date. THis library is not being actively developed, and I would not suggest relying on it.
